"""Stable, lazy public facade for default-off AIDT worktree ownership."""

from __future__ import annotations

from typing import TYPE_CHECKING

from .contract import (
    AIDT_COMPLETION_AUTHORIZATION_SCHEMA,
    AIDT_WORKTREE_ACTIVATION_SCHEMA,
    AIDT_WORKTREE_ATTEMPT_SCHEMA,
    AIDT_WORKTREE_BASE_REF,
    AIDT_WORKTREE_OWNERSHIP_SCHEMA,
    AIDT_WORKTREE_SCHEMA,
    AidtWorktreeFailure,
    AidtWorktreeResult,
    AidtWorktreeSettings,
    CompletionAuthorization,
    DelegateDisposition,
    DelegateResult,
    StableMetadataPaths,
    StableWorktreePaths,
    change_kind_for_issue_type,
    common_git_lock_path,
    contained_workspace_path,
    derive_aidt_branch,
    load_aidt_worktree_settings,
    stable_metadata_paths,
    stable_worktree_paths,
    validate_aidt_branch,
)

if TYPE_CHECKING:
    from .git_state import (
        BinaryRunner,
        BindingObserver,
        FETCH_ARGV,
        FetchResult,
        GIT_FETCH_TIMEOUT_SECONDS,
        GIT_GLOBAL_OPTIONS,
        GIT_LOCAL_TIMEOUT_SECONDS,
        GIT_STDERR_CAP,
        GIT_STDOUT_CAP,
        GitCommandResult,
        PreparedRecoveryProof,
        ReadyRecoveryProof,
        RemovedRecoveryProof,
        RefRecord,
        RepositoryIdentity,
        RepositoryState,
        StatusEntry,
        TargetArtifactDisposition,
        TicketWorktreeState,
        WorktreeRegistration,
        add_worktree,
        base_is_ancestor,
        canonical_origin_digest,
        classify_target_artifacts,
        default_binary_runner,
        fetch_production_base,
        git_environment,
        observe_repository_identity,
        observe_repository_state,
        observe_ticket_worktree,
        parse_ref_listing,
        parse_status_porcelain_v2,
        parse_worktree_porcelain,
        prove_prepared_recovery,
        prove_ready_recovery,
        prove_removed_recovery,
        remove_worktree,
        validate_create_delta,
        validate_fetch_delta,
        validate_remove_delta,
        verify_service_binding,
    )
    from .manifest import (
        ActivationRecord,
        AidtWorktreeManifest,
        AttemptAdmission,
        AttemptRecord,
        DurabilityResult,
        OwnershipRecord,
        PostProof,
        PreProof,
        RegistryDiscovery,
        RemovalProof,
        RepositorySnapshot,
        RouteScope,
        activate_registry,
        advance_attempt_phase,
        admit_attempt,
        advisory_lock,
        canonical_json_bytes,
        decode_canonical_json,
        discover_registry,
        evaluate_attempt_admission,
        initial_attempt_record,
        manifest_from_dict,
        next_failure_record,
        ordered_worktree_locks,
        persist_attempt,
        persist_manifest,
        persist_ownership,
        read_activation,
        read_attempt,
        read_manifest,
        read_optional_attempt,
        read_optional_manifest,
        read_optional_ownership,
        read_ownership,
        ready_attempt_record,
        registry_recognizes_identifier,
        registry_recognizes_path,
    )
    from .provisioner import (
        ActiveCompletionLease,
        AidtProvisioningAdmission,
        AidtRunGuard,
        AidtWorktreeProvisioner,
        CompletionAuthority,
        DenyAllCompletionAuthority,
        PreparedAidtWorktree,
    )
    from .runtime import AidtWorktreeGeneration, AidtWorktreeHealth, AidtWorktreeRuntime

_MANIFEST_EXPORTS = frozenset(
    {
        "ActivationRecord",
        "AidtWorktreeManifest",
        "AttemptAdmission",
        "AttemptRecord",
        "DurabilityResult",
        "OwnershipRecord",
        "PostProof",
        "PreProof",
        "RegistryDiscovery",
        "RemovalProof",
        "RepositorySnapshot",
        "RouteScope",
        "activate_registry",
        "advance_attempt_phase",
        "admit_attempt",
        "advisory_lock",
        "canonical_json_bytes",
        "decode_canonical_json",
        "discover_registry",
        "evaluate_attempt_admission",
        "initial_attempt_record",
        "manifest_from_dict",
        "next_failure_record",
        "ordered_worktree_locks",
        "persist_attempt",
        "persist_manifest",
        "persist_ownership",
        "read_activation",
        "read_attempt",
        "read_manifest",
        "read_optional_attempt",
        "read_optional_manifest",
        "read_optional_ownership",
        "read_ownership",
        "ready_attempt_record",
        "registry_recognizes_identifier",
        "registry_recognizes_path",
    }
)

_GIT_STATE_EXPORTS = frozenset(
    {
        "FETCH_ARGV",
        "BinaryRunner",
        "BindingObserver",
        "FetchResult",
        "GIT_FETCH_TIMEOUT_SECONDS",
        "GIT_GLOBAL_OPTIONS",
        "GIT_LOCAL_TIMEOUT_SECONDS",
        "GIT_STDERR_CAP",
        "GIT_STDOUT_CAP",
        "GitCommandResult",
        "PreparedRecoveryProof",
        "ReadyRecoveryProof",
        "RemovedRecoveryProof",
        "RefRecord",
        "RepositoryIdentity",
        "RepositoryState",
        "StatusEntry",
        "TargetArtifactDisposition",
        "TicketWorktreeState",
        "WorktreeRegistration",
        "add_worktree",
        "base_is_ancestor",
        "canonical_origin_digest",
        "classify_target_artifacts",
        "default_binary_runner",
        "fetch_production_base",
        "git_environment",
        "observe_repository_identity",
        "observe_repository_state",
        "observe_ticket_worktree",
        "parse_ref_listing",
        "parse_status_porcelain_v2",
        "parse_worktree_porcelain",
        "prove_prepared_recovery",
        "prove_ready_recovery",
        "prove_removed_recovery",
        "remove_worktree",
        "validate_create_delta",
        "validate_fetch_delta",
        "validate_remove_delta",
        "verify_service_binding",
    }
)

_PROVISIONER_EXPORTS = frozenset(
    {
        "ActiveCompletionLease",
        "AidtProvisioningAdmission",
        "AidtRunGuard",
        "AidtWorktreeProvisioner",
        "CompletionAuthority",
        "DenyAllCompletionAuthority",
        "PreparedAidtWorktree",
    }
)

_RUNTIME_EXPORTS = frozenset(
    {"AidtWorktreeGeneration", "AidtWorktreeHealth", "AidtWorktreeRuntime"}
)

__all__ = [
    "AIDT_COMPLETION_AUTHORIZATION_SCHEMA",
    "AIDT_WORKTREE_ACTIVATION_SCHEMA",
    "AIDT_WORKTREE_ATTEMPT_SCHEMA",
    "AIDT_WORKTREE_BASE_REF",
    "AIDT_WORKTREE_OWNERSHIP_SCHEMA",
    "AIDT_WORKTREE_SCHEMA",
    "ActivationRecord",
    "ActiveCompletionLease",
    "AidtProvisioningAdmission",
    "AidtRunGuard",
    "AidtWorktreeFailure",
    "AidtWorktreeGeneration",
    "AidtWorktreeHealth",
    "AidtWorktreeManifest",
    "AidtWorktreeProvisioner",
    "AidtWorktreeResult",
    "AidtWorktreeRuntime",
    "AidtWorktreeSettings",
    "BinaryRunner",
    "BindingObserver",
    "AttemptAdmission",
    "AttemptRecord",
    "CompletionAuthorization",
    "CompletionAuthority",
    "DelegateDisposition",
    "DelegateResult",
    "DurabilityResult",
    "DenyAllCompletionAuthority",
    "FETCH_ARGV",
    "FetchResult",
    "GIT_FETCH_TIMEOUT_SECONDS",
    "GIT_GLOBAL_OPTIONS",
    "GIT_LOCAL_TIMEOUT_SECONDS",
    "GIT_STDERR_CAP",
    "GIT_STDOUT_CAP",
    "GitCommandResult",
    "PreparedRecoveryProof",
    "ReadyRecoveryProof",
    "RemovedRecoveryProof",
    "RefRecord",
    "RepositoryIdentity",
    "RepositoryState",
    "StatusEntry",
    "OwnershipRecord",
    "PostProof",
    "PreProof",
    "PreparedAidtWorktree",
    "RegistryDiscovery",
    "RemovalProof",
    "RepositorySnapshot",
    "RouteScope",
    "StableMetadataPaths",
    "StableWorktreePaths",
    "TargetArtifactDisposition",
    "TicketWorktreeState",
    "WorktreeRegistration",
    "activate_registry",
    "advance_attempt_phase",
    "add_worktree",
    "base_is_ancestor",
    "admit_attempt",
    "advisory_lock",
    "canonical_json_bytes",
    "canonical_origin_digest",
    "classify_target_artifacts",
    "change_kind_for_issue_type",
    "common_git_lock_path",
    "contained_workspace_path",
    "decode_canonical_json",
    "derive_aidt_branch",
    "default_binary_runner",
    "discover_registry",
    "evaluate_attempt_admission",
    "initial_attempt_record",
    "fetch_production_base",
    "git_environment",
    "load_aidt_worktree_settings",
    "manifest_from_dict",
    "next_failure_record",
    "ordered_worktree_locks",
    "observe_repository_identity",
    "observe_repository_state",
    "observe_ticket_worktree",
    "parse_ref_listing",
    "parse_status_porcelain_v2",
    "parse_worktree_porcelain",
    "prove_prepared_recovery",
    "prove_ready_recovery",
    "prove_removed_recovery",
    "remove_worktree",
    "persist_attempt",
    "persist_manifest",
    "persist_ownership",
    "read_activation",
    "read_attempt",
    "read_manifest",
    "read_optional_attempt",
    "read_optional_manifest",
    "read_optional_ownership",
    "read_ownership",
    "ready_attempt_record",
    "registry_recognizes_identifier",
    "registry_recognizes_path",
    "stable_metadata_paths",
    "stable_worktree_paths",
    "validate_create_delta",
    "validate_fetch_delta",
    "validate_remove_delta",
    "validate_aidt_branch",
    "verify_service_binding",
]


def __getattr__(name: str) -> object:
    if name in _MANIFEST_EXPORTS:
        from . import manifest as module
    elif name in _GIT_STATE_EXPORTS:
        from . import git_state as module
    elif name in _PROVISIONER_EXPORTS:
        from . import provisioner as module
    elif name in _RUNTIME_EXPORTS:
        from . import runtime as module
    else:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(module, name)
    globals()[name] = value
    return value
